name: ojos_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # data layer
  get_it: ^7.2.0
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  cupertino_icons: ^1.0.3
  sembast: ^3.1.0+2
  fluttertoast: ^8.0.8
  connectivity: ^3.0.6
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.9
  chewie: ^1.2.2
  sqflite: any
  firebase_messaging: ^10.0.4

  # UI Layer
  flutter_spinkit: ^5.0.0

  flutter_svg: ^1.0.0
  carousel_slider: ^4.0.0
  percent_indicator: ^3.0.1
  shared_preferences: ^2.0.13
  #open_whatsapp: ^0.0.1
  flutter_launcher_icons: ^0.9.1
  persistent_bottom_nav_bar: ^4.0.2
  get: ^4.3.4
  smooth_page_indicator: ^0.3.0-nullsafety.0
  clippy_flutter: ^2.0.0-nullsafety.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  # Is not supported anu more instead we use liquid_ui
  # residemenu: ^1.3.7
  # Liquid is an open source UI toolkit for developing cross platform apps in Flutter.
  # Quickly create apps for Android, IOS, Web or Desktop with our powerful grid system,
  # text processor, forms, extensive prebuilt components and dozens of utilities.
  shrink_sidemenu: ^2.0.0+1-null-safety
  liquid_ui: ^1.0.0+9

  expandable: ^5.0.1
  steps_indicator: ^1.3.0
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.6
  #  google_map_location_picker: ^4.1.5
  place_picker: ^0.9.20-nullsafety
  geolocator: ^7.4.0
  permission_handler: ^9.2.0
  geocoding: ^2.0.0
  image_picker: ^0.8.3+1
  share: ^2.0.4
  http: ^0.13.4
  flutter_screenutil: ^5.3.1
  #  custom_switch: ^0.0.1
  #  flutter_verification_code: ^0.2.1
  # notification
  # flutter_local_notifications: ^9.0.0
  google_maps_place_picker: ^2.0.0-nullsafety.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  intl: ^0.17.0
  flutter_share: ^2.0.0
  firebase_dynamic_links: ^4.0.3

dependency_overrides:
  permission_handler: ^9.2.0
  firebase_messaging_platform_interface: 3.1.6
  firebase_crashlytics_platform_interface: 3.1.13
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  firebase_analytics_platform_interface: 3.0.5
  firebase_remote_config_platform_interface: 1.0.5
  firebase_dynamic_links_platform_interface: 0.2.0+5
  firebase_performance_platform_interface: 0.1.0+5
  firebase_app_installations_platform_interface: 0.1.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  dropdown_search: ^1.0.3
  wc_flutter_share: ^0.4.0

  change_app_package_name:

#  # data layer
#  get_it: ^5.0.1
#  flutter_bloc: ^6.0.6
#  equatable: ^1.2.5
#  dartz: ^0.9.2
#  dio: ^3.0.10
#  hive: ^1.4.4+1
#  hive_flutter: ^0.3.1
#  path_provider: ^1.6.21
#  provider: ^4.3.2+2
#  cupertino_icons: ^1.0.0
#  sembast: ^2.4.8+1
#  fluttertoast: ^7.1.1
#  shared_preferences: ^0.5.12+2
#  data_connection_checker: ^0.3.4
#  connectivity: ^0.4.9+5
#  modal_progress_hud: ^0.1.3
##  pull_to_refresh: ^1.6.4
#  shimmer: ^1.1.2
#  cached_network_image: ^2.3.2+1
#  url_launcher: ^5.7.4
#  chewie: ^0.12.2
#
#  # UI Layer
#  flutter_screenutil: ^3.1.1
#  flutter_spinkit: ^4.1.2+1
#  flutter_icons: ^1.1.0
#  flutter_svg: ^0.19.0
#  flutter_swiper: ^1.1.6
#  carousel_slider: ^2.3.1
#  percent_indicator: ^2.1.7+4
#  flutter_open_whatsapp: ^0.1.2
#  flutter_launcher_icons: ^0.8.1
#  persistent_bottom_nav_bar: ^3.1.0
#  get: ^3.24.0
#  smooth_page_indicator: ^0.2.0
#  clippy_flutter: ^1.1.1
#  scrollable_positioned_list: ^0.1.8
#  residemenu: ^1.3.7
#  expandable: ^4.1.4
#  steps_indicator: ^1.1.0
#  flutter_rating_bar: ^3.2.0+1
#  google_maps_flutter: ^1.0.10
##  google_map_location_picker: ^4.1.5
#  place_picker: ^0.9.17
#  geolocator: ^6.1.13
#  permission_handler: ^5.0.1+1
#  geocoding: ^1.0.5
#  image_picker: ^0.6.2+3
#  share: ^0.6.3+5
##  custom_switch: ^0.0.1
##  flutter_verification_code: ^0.2.1
#  # notification
#  firebase_messaging: ^6.0.16
#  flutter_local_notifications: ^1.4.4+1
#  google_maps_place_picker: ^1.0.1
#  firebase_auth: ^0.20.1
#  firebase_core: ^0.7.0
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  build_runner: ^1.7.4
#  json_serializable: ^3.2.3
#  font_awesome_flutter:
#  dropdown_search:
#  change_app_package_name:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/ojos_logo_app.png"
flutter:
  uses-material-design: true

  assets:
    - assets/locales/
    - assets/images/maroof.png
    - assets/images/icons/
    - assets/images/
    - assets/images/icons/svg/
    - assets/images/icons/png/
    - assets/images/logo/
    - assets/images/image/
    - assets/images/temp/

  fonts:
    - family: Hacen Tunisia Lt
      fonts:
        - asset: assets/font_family/Hacen-Tunisia-Lt.ttf

    - family: Almarai
      fonts:
        - asset: assets/font_family/Almarai-Regular.ttf
